.Dd 12 Фев 2025
.Dt DUBLER 1
.Os
.Sh NAME
.Nm bayan
.Nd Поиск дублирующихся файлов в указанных директориях.
.Sh SYNOPSIS
.Nm
.Op Fl d Ar directory ...
.Op Fl e Ar exclude ...
.Op Fl m Ar mask ...
.Op Fl s Ar min-size
.Op Fl b Ar block-size
.Op Fl a Ar algorithm
.Sh DESCRIPTION
The utility 
.Nm
сканирует указанные директории и ищет дублирующиеся файлы путём сравнения хэш-значений блоков данных.
.Pp
Основные параметры:
.Bl -tag -width Ds
.It Fl d Ar directory
Указывает директорию для сканирования.
.It Fl e Ar exclude
Указывает путь или шаблон директории, которую необходимо исключить из сканирования.
.It Fl m Ar mask
Фильтр по маске файла (например, "*.txt").
.It Fl s Ar min-size
Минимальный размер файла (в байтах), который будет учитываться.
.It Fl b Ar block-size
Размер блока для чтения файла.
.It Fl a Ar algorithm
Алгоритм хэширования ("crc32" или "md5").
.El
.Sh OPTIONS
.Pp
-h, --help
Выводит это сообщение помощи.
.Sh EXAMPLES
.Pp
Для поиска дубликатов в директории /home/user с исключением /home/user/tmp:
.Pp
.nf
bayan -d /home/user -e /home/user/tmp -m "*.txt" -s 1024 -b 4096 -a md5
.fi
.Sh SEE ALSO
Другие утилиты для работы с файлами, например, 
.BR fdupes (1),
.BR rmlint (1).
